# Generated by Django 4.2.7 on 2023-11-26 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Admin')),
                ('nom_prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=8)),
                ('photo', models.ImageField(blank=True, default='default_profile_picture.png', upload_to=polls.models.filepathAdmins)),
                ('statutAdmin', models.CharField(blank=True, choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Deactivated', max_length=11)),
                ('token', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Client')),
                ('nomprenom', models.CharField(blank=True, max_length=50)),
                ('cin_passport', models.CharField(blank=True, max_length=12)),
                ('numeroparmis', models.CharField(blank=True, max_length=50)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=255)),
                ('paye', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('numerorue', models.CharField(blank=True, max_length=50)),
                ('nomentrprise', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, default='default_profile_picture.png', upload_to=polls.models.filepathClient_Photo)),
                ('photo_cin_passport', models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepathClient_Cin_Passport)),
                ('photo_parmis', models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepathClient_Parmis)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('statutClient', models.CharField(blank=True, choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Deactivated', max_length=11)),
                ('token', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Demande')),
                ('type', models.CharField(blank=True, choices=[('Reservation', 'Reservation'), ('Exurcion', 'Exurcion'), ('Transfer', 'Transfer')], default='Reservation', max_length=11)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('etat', models.CharField(blank=True, choices=[('Attente', 'Attente'), ('EnCours', 'En Cours'), ('Terminer', 'Terminer'), ('Annuler', 'Annuler')], default='Attente', max_length=11)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.client')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ListExurcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ListExurcion')),
                ('address_depart', models.CharField(blank=True, choices=[('De Hammamet a Tunis Carthage', 'De Hammamet a Tunis Carthage'), ('De Hammamet a Kairoun', 'De Hammamet a Kairoun'), ('De Hammamet a Sousse', 'De Hammamet a Sousse'), ('De Hammamet a Hammamet Yasmine', 'De Hammamet a Hammamet Yasmine')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ListTransfer')),
                ('address_depart', models.CharField(blank=True, choices=[('Hammamet', 'Hammamet'), ('Tunisie', 'Tunisie'), ('Enfidha', 'Enfidha'), ('Monastir', 'Monastir'), ('Sfax', 'Sfax'), ('Sousse', 'Sousse')], max_length=8)),
                ('address_fin', models.CharField(blank=True, choices=[('Hammamet', 'Hammamet'), ('Tunisie', 'Tunisie'), ('Enfidha', 'Enfidha'), ('Monastir', 'Monastir'), ('Sfax', 'Sfax'), ('Sousse', 'Sousse')], max_length=8)),
                ('prix', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Marquer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Marquer')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, default='default_profile_picture.png', null=True, upload_to=polls.models.filepathMarquer)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Post')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('descriptions', models.TextField(blank=True, max_length=255)),
                ('date_depart', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_fin', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 29, 13, 1, 26, 973986))),
                ('lien', models.URLField(default='https://www.tiktok.com/@neapolis.car', max_length=255)),
                ('photo', models.ImageField(default='default_image.jpg', upload_to=polls.models.filepathPost)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('numero_series', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Voiture')),
                ('modele', models.CharField(blank=True, max_length=50)),
                ('class_voiture', models.CharField(blank=True, max_length=10)),
                ('annee', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('boite', models.CharField(blank=True, max_length=10)),
                ('nb_seats', models.IntegerField(blank=True, default=0)),
                ('nb_bags', models.IntegerField(blank=True, default=0)),
                ('nb_ports', models.IntegerField(blank=True, default=0)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('etat', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('caution', models.FloatField(blank=True, default=0)),
                ('prix_jour', models.FloatField(blank=True, default=0)),
                ('photo', models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepath)),
                ('id_marquer', models.ForeignKey(blank=True, db_column='id', on_delete=django.db.models.deletion.CASCADE, to='polls.marquer')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Transfer')),
                ('date_depar', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 13, 1, 26, 980023))),
                ('id_ListTransfer', models.ForeignKey(blank=True, db_column='id_ListTransfer', on_delete=django.db.models.deletion.CASCADE, to='polls.listtransfer')),
                ('id_demande', models.ForeignKey(blank=True, db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='polls.demande')),
                ('numero_series', models.ForeignKey(blank=True, db_column='numero_series', on_delete=django.db.models.deletion.CASCADE, to='polls.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Service')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('descreptions', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.FloatField(blank=True, default=0)),
                ('id_demande', models.ForeignKey(blank=True, db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='polls.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Reservation')),
                ('bureau_predre_la_voiture', models.CharField(blank=True, max_length=100)),
                ('bureau_deposer_la_voiture', models.CharField(blank=True, max_length=100)),
                ('date_depar', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_arriver', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 2, 13, 1, 26, 977975))),
                ('id_demande', models.ForeignKey(blank=True, db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='polls.demande')),
                ('numero_series', models.ForeignKey(blank=True, db_column='numero_series', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Paiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Paiment')),
                ('prix', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Check', 'Check')], default='Card', max_length=8)),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
                ('id_demande', models.ForeignKey(blank=True, db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='polls.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Options')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('descriptions', models.TextField(blank=True, max_length=255)),
                ('numero_series', models.ForeignKey(blank=True, db_column='numero_series', on_delete=django.db.models.deletion.CASCADE, to='polls.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('idPhoto', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Identifiant Gallery')),
                ('photo', models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepathGallery)),
                ('titleGallery', models.CharField(blank=True, max_length=2048, unique=True)),
                ('listExurcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.listexurcion')),
            ],
        ),
        migrations.CreateModel(
            name='Exurcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Exurcion')),
                ('date_depar', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 13, 1, 26, 978973))),
                ('id_ListExurcion', models.ForeignKey(blank=True, db_column='id_ListExurcion', on_delete=django.db.models.deletion.CASCADE, to='polls.listexurcion')),
                ('id_demande', models.ForeignKey(blank=True, db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='polls.demande')),
                ('numero_series', models.ForeignKey(blank=True, db_column='numero_series', on_delete=django.db.models.deletion.CASCADE, to='polls.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.djangocontenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authuser')),
            ],
        ),
        migrations.AddField(
            model_name='authpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.djangocontenttype'),
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.authpermission')),
            ],
        ),
        migrations.CreateModel(
            name='Annulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Annulation')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('id_demande', models.ForeignKey(db_column='id_demand', on_delete=django.db.models.deletion.CASCADE, to='polls.demande')),
            ],
        ),
    ]
