# Generated by Django 4.2.4 on 2023-09-23 09:26

import datetime
from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to=polls.models.filepathAdmins),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to=polls.models.filepathClient_Photo),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo_cin_passport',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepathClient_Cin_Passport),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo_parmis',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepathClient_Parmis),
        ),
        migrations.AlterField(
            model_name='exurcion',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 25, 10, 26, 53, 291332)),
        ),
        migrations.AlterField(
            model_name='listexurcion',
            name='address_depart',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='listexurcion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ListExurcion'),
        ),
        migrations.AlterField(
            model_name='listtransfer',
            name='address_depart',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='listtransfer',
            name='address_fin',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='marquer',
            name='logo',
            field=models.ImageField(blank=True, default='default_profile_picture.png', null=True, upload_to=polls.models.filepathMarquer),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 10, 26, 53, 291332)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default_image.jpg', upload_to=polls.models.filepathPost),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_arriver',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 29, 10, 26, 53, 291332)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 25, 10, 26, 53, 291332)),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to=polls.models.filepath),
        ),
    ]
