# Generated by Django 4.2.4 on 2023-09-23 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_admin_photo_alter_client_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exurcion',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 25, 10, 29, 51, 947980)),
        ),
        migrations.AlterField(
            model_name='listexurcion',
            name='address_depart',
            field=models.CharField(blank=True, choices=[('De Hammamet a Tunis Carthage', 'De Hammamet a Tunis Carthage'), ('De Hammamet a Kairoun', 'De Hammamet a Kairoun'), ('De Hammamet a Sousse', 'De Hammamet a Sousse'), ('De Hammamet a Hammamet Yasmine', 'De Hammamet a Hammamet Yasmine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listtransfer',
            name='address_depart',
            field=models.CharField(blank=True, choices=[('Hammamet', 'Hammamet'), ('Tunisie', 'Tunisie'), ('Enfidha', 'Enfidha'), ('Monastir', 'Monastir'), ('Sfax', 'Sfax'), ('Sousse', 'Sousse')], max_length=8),
        ),
        migrations.AlterField(
            model_name='listtransfer',
            name='address_fin',
            field=models.CharField(blank=True, choices=[('Hammamet', 'Hammamet'), ('Tunisie', 'Tunisie'), ('Enfidha', 'Enfidha'), ('Monastir', 'Monastir'), ('Sfax', 'Sfax'), ('Sousse', 'Sousse')], max_length=8),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 10, 29, 51, 947980)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_arriver',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 29, 10, 29, 51, 947980)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 25, 10, 29, 51, 947980)),
        ),
    ]
