# Generated by Django 4.2.4 on 2023-09-24 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_exurcion_date_depar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='exurcion',
        ),
        migrations.AddField(
            model_name='gallery',
            name='listExurcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.listexurcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exurcion',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 16, 13, 48, 797996)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 27, 16, 13, 48, 797996)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_arriver',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 30, 16, 13, 48, 797996)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 16, 13, 48, 797996)),
        ),
    ]
