# Generated by Django 4.2.4 on 2023-09-25 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_exurcion_date_depar_alter_gallery_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exurcion',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 27, 19, 10, 50, 514845)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 28, 19, 10, 50, 514845)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_arriver',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 1, 19, 10, 50, 514845)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date_depar',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 27, 19, 10, 50, 530462)),
        ),
    ]
